version: "3.9"
services:
  beston-poc:
    build: 
        context: .
        dockerfile: Dockerfile
    image: bestonacr.azurecr.io/beston-poc:latest
    container_name: beston-poc-container
    restart: unless-stopped
    ports:
      - "3080:3001"
